### PR TITLE
Implemented clearHistory method to sdb

### PR DESCRIPTION
**Pull request by mkusaka**
First, thank's to useful library :)

I implemented a history clear function in sdb to solve a problem that occurs during image editing use cases

In such a use case, sdb#fillImageByDataURL is called before the user action, but the process by sdb#fillImageByDataURL is recorded in the history. As a result, when the user performs a "back" operation implemented by sdb#undo(), a blank screen is displayed.

This problem can be solved by clearing the history in the case of editing, so this is why we have implemented it this way.

### CODE REVIEW

**Comment by leader22** [comment]
Hi. ✋🏻 

Would you give me an example code or repro and expectation for your usecase?

> sdb#fillImageByDataURL is called before the user action, but the process by sdb#fillImageByDataURL is recorded in the history. As a result, when the user performs a "back" operation implemented by sdb#undo(), a blank screen is displayed.

I'm not sure what this part means.

Does it mean,

- at first, call `fillImageByDataURL()`
  - and this is `async`, so it's not resolved yet
  - history = []
- and user starts drawing immediately
  - triggers history update too
  - history = [drawing]
- promise of `fillImageByDataURL` has resolved now
  - triggers history update(delayed)
  - history = [drawing, fillImage]
- `undo()`
  - history = [drawing]

...?

**Comment by mkusaka** [comment]
@leader22 Thank you for your review.
Ok. Here is my use case.

1. at first , create canvas and call `fillImageByDataURL()` with argument ImageA
	- and async function resolved
	- history = [drawing]
	- canvas filled with ImageA
	- (This process done before user action. Because this is edit image pattern.)
2. and user press back button with `undo()`
    - history = []
    - canvas will be blank ← The expected behavior is that the image will remain in the canvas.

I made example code here
https://github.com/mkusaka/simple-drawing-board.js/tree/sample

clone & `npx http-server .` & open `http://localhost:8080/__htmls__/styled.html`

1. user start with following state
	- スクリーンショット 2022-04-23 23 22 59

2. when press `undo` button, editing image has gone....()
     - スクリーンショット 2022-04-23 23 23 08

Also, I want to support edit(includes undo & redo) this image
スクリーンショット 2022-04-23 23 23 17

**Comment by leader22** [comment]
Oh, that makes sense!

The points are,

- the first `fillImageByDataURL` is default state
  - not a part of editing process
  - not need to be included in history
- `undo` itself works as expected
  - but it's inconvenient for your case

Right?

If so, passing pre-painted `canvas` to `sdb.create($el)` may make your expect behavior possible.

```diff
-    window.sdb.fillImageByDataURL(d).then(() => console.log("complete"))
+    window.sdb.fillImageByDataURL(d).then(() => {
+      window.sdb = create(c);
+    })
```

**Comment by mkusaka** [comment]
@leader22 Oh! Thats what I want. Thank you.

**Comment by mkusaka** [comment]
I'll close the PR now that the question has been answered. Thanks a lot!.

**Pull request closed without merging**
